version: "3"
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

  library-service:
    container_name: "library-service"
    networks:
      - my-network
    build:
      context: ./libraryService
      dockerfile: Dockerfile
    depends_on:
      - "mongodb"
    restart: always
    ports:
      - "8081:8081"

  api-gateway:
    container_name: api-gateway
    networks:
      - my-network
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - "library-service"
    restart: always
    ports:
      - "8080:8080"
networks:
  my-network: